// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qinskqqlkmvlfuyvaliw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpbnNrcXFsa212bGZ1eXZhbGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1Mjg2NDgsImV4cCI6MjA5MDEwNDY0OH0.meC00PFJyMDoF6I8rOF0PSpk_-7hTnyrajmr955BHw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});